#ifndef INCLUDES_TARANTOOL_BOX_PROMOTE_H
#define INCLUDES_TARANTOOL_BOX_PROMOTE_H
/*
 * Copyright 2010-2018, Tarantool AUTHORS, please see AUTHORS file.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * 1. Redistributions of source code must retain the above
 *    copyright notice, this list of conditions and the
 *    following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY <COPYRIGHT HOLDER> ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * <COPYRIGHT HOLDER> OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
 * THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
#include "tt_uuid.h"
#include "diag.h"
#include "fiber_cond.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct info_handler;

enum promote_msg_type {
	PROMOTE_MSG_BEGIN = 0,
	PROMOTE_MSG_STATUS,
	PROMOTE_MSG_SYNC,
	PROMOTE_MSG_SUCCESS,
	PROMOTE_MSG_ERROR,
	promote_msg_type_MAX,
};

/**
 * Promotion message. The unit of communication between an
 * initiator, an old master and watchers.
 */
struct promote_msg {
	/**
	 * Round ID. Together with round UUID composes an unique
	 * round identifier. For details see promotion_state.
	 */
	int round_id;
	/** Promotion round UUID, generated by the initiator. */
	struct tt_uuid round_uuid;
	/** UUID of the message sender. */
	struct tt_uuid source_uuid;
	/**
	 * Timestamp of the message send time by the sender clock.
	 * Just debug attribute, that is persisted.
	 */
	double ts;
	/** Promotion message type. */
	enum promote_msg_type type;
	/** Step of the round on which the message was sent. */
	int step;
	/**
	 * Depending on the message type, different attributes
	 * are available in the message.
	 */
	union {
		struct {
			/**
			 * 'Begin' promotion message carries
			 * quorum and timeout of the new round
			 * among other common things above.
			 */
			int quorum;
			double timeout;
		} begin;
		struct {
			/**
			 * 'Status' message carries the sender
			 * role.
			 */
			bool is_master;
		} status;
		struct {
			/**
			 * 'Error' message carries the error code
			 * and message to be set in diag.
			 */
			int code;
			const char *message;
		} error;
	};
};

/**
 * Decode the MessagePack encoded promotion message into @a msg.
 * @param data MessagePack data to decode. Tuple from _promotion.
 * @param[out] msg Object to fill up.
 *
 * @retval -1 Error during decoding.
 * @retval 0 Success.
 */
int
promote_msg_decode(const char *data, struct promote_msg *msg);

/**
 * Process the promotion message, update the promotion state. The
 * processing is executed on commit of @a msg.
 * @param msg Message to process.
 */
void
promote_process(const struct promote_msg *msg);

/**
 * Promote the current instance to be a master in the fullmesh
 * master-master cluster. The old master, if exists, is demoted.
 * Once a promotion attempt is done anywhere, manual change of
 * read_only flag is disabled.
 * @param timeout Timeout during which the promotion should be
 *        finished.
 * @param quorum The promotion quorum of instances who should
 *        approve the promotion and sync with the old master
 *        before demotion. The quorum should be at least half of
 *        the cluster size + 1 and include the old master. If an
 *        old master does not exist, then the quorum is ignored
 *        and the promotion waits for 100% of the cluster
 *        members.
 *
 * @retval -1 Error.
 * @retval 0 Success.
 */
int
box_ctl_promote(double timeout, int quorum);

/**
 * Show status of the current active promotion round or the last
 * finished one.
 * @param info Info handler to collect the info into.
 */
void
box_ctl_promote_info(struct info_handler *info);

/**
 * Remove all the promotion rounds from the history. That allows
 * to change read_only manually again.
 */
int
box_ctl_promote_reset(void);

/** Initialize the promotion subsystem. */
int
box_ctl_promote_init(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* INCLUDES_TARANTOOL_BOX_PROMOTE_H */
